"""empty message

Revision ID: f6456571c2d0
Revises: c76121de740e
Create Date: 2018-12-04 09:00:13.589900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6456571c2d0'
down_revision = 'c76121de740e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('confirmation', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange', 'confirmation')
    # ### end Alembic commands ###
