"""empty message

Revision ID: 6861bcb97478
Revises: 2ed2ac8287b8
Create Date: 2018-12-29 21:09:17.501044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6861bcb97478'
down_revision = '2ed2ac8287b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_member', 'invited_by_id', nullable=False, new_column_name='inviter_id')
    op.drop_constraint('team_member_invited_by_id_fkey', 'team_member', type_='foreignkey')
    op.create_foreign_key(None, 'team_member', 'app_user', ['inviter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_member', 'inviter_id', nullable=False, new_column_name='invited_by_id')
    op.drop_constraint('team_member_inviter_id_fkey', 'team_member', type_='foreignkey')
    op.create_foreign_key('team_member_invited_by_id_fkey', 'team_member', 'app_user', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###
