"""empty message

Revision ID: ac8ef53ba759
Revises: 9f2725a01e4c
Create Date: 2018-12-10 06:46:25.347910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8ef53ba759'
down_revision = '9f2725a01e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('router', sa.String(length=32), nullable=False))
    op.drop_column('notification', 'router_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('router_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('notification', 'router')
    # ### end Alembic commands ###
