"""empty message

Revision ID: 462216f1d4a2
Revises: 4a72104a5108
Create Date: 2018-12-09 00:13:53.430772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '462216f1d4a2'
down_revision = '4a72104a5108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('notification', sa.Column('router_id', sa.String(length=32), nullable=False))
    op.drop_column('notification', 'timezone')
    op.drop_column('notification', 'trigger_type')
    op.drop_column('notification', 'tag')
    op.drop_column('notification', 'end_date')
    op.drop_column('notification', 'jitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('jitter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('tag', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('trigger_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('timezone', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('notification', 'router_id')
    op.drop_column('notification', 'active')
    # ### end Alembic commands ###
