"""empty message

Revision ID: 0b122c5a07a7
Revises: b9d4a43b7ab2
Create Date: 2018-12-20 20:45:29.772749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b122c5a07a7'
down_revision = 'b9d4a43b7ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_router_user_active', 'notification', ['user_id', 'router', 'active'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_router_user_active', 'notification', type_='unique')
    # ### end Alembic commands ###
