"""empty message

Revision ID: c76121de740e
Revises: 76b952dfbdc8
Create Date: 2018-12-03 16:46:48.375265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c76121de740e'
down_revision = '76b952dfbdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('actions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('exchange', sa.Column('inbound_format', sa.String(length=32), nullable=False, server_default='*'))
    op.add_column('exchange', sa.Column('next_router_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange', 'next_router_id')
    op.drop_column('exchange', 'inbound_format')
    op.drop_column('exchange', 'actions')
    # ### end Alembic commands ###
