"""empty message

Revision ID: 2ed2ac8287b8
Revises: 0b122c5a07a7
Create Date: 2018-12-23 01:57:55.916685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed2ac8287b8'
down_revision = '0b122c5a07a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
