"""empty message

Revision ID: 0063af4db466
Revises: b4a494dd328e
Create Date: 2019-03-28 17:33:55.662175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0063af4db466'
down_revision = 'b4a494dd328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('fir_auth_id', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'app_user', ['fir_auth_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='unique')
    op.drop_column('app_user', 'fir_auth_id')
    # ### end Alembic commands ###
