"""empty message

Revision ID: 02dcb9c673d9
Revises: e061f9108358
Create Date: 2019-04-03 21:12:58.809864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02dcb9c673d9'
down_revision = 'e061f9108358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'fir_push_notif_token')
    op.alter_column('app_user', 'firebase_token', new_column_name='fir_push_notif_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'fir_push_notif_token', new_column_name='firebase_token')
    op.add_column('app_user', sa.Column('fir_push_notif_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
