"""empty message

Revision ID: 2ae0b58173e4
Revises: e9184708d96c
Create Date: 2019-03-01 05:07:54.731209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae0b58173e4'
down_revision = 'e9184708d96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'google_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('task', sa.Column('exchange_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'exchange', ['exchange_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'exchange_id')
    op.alter_column('app_user', 'google_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
