"""empty message

Revision ID: 67c1c289692e
Revises: dc6c3b968d40
Create Date: 2019-02-15 02:15:37.429324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c1c289692e'
down_revision = 'dc6c3b968d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_exchange_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'exchange_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_exchange_id_fkey', 'task', 'exchange', ['exchange_id'], ['id'])
    # ### end Alembic commands ###
