"""empty message

Revision ID: 1fb32fc35709
Revises: 640f046a2689
Create Date: 2019-03-13 02:30:16.439327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb32fc35709'
down_revision = '640f046a2689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'points_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('points_total', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
