"""empty message

Revision ID: e061f9108358
Revises: 90bbfe8896f6
Create Date: 2019-04-03 19:47:57.963086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e061f9108358'
down_revision = '90bbfe8896f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('fir_push_notif_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'fir_push_notif_token')
    # ### end Alembic commands ###
