"""empty message

Revision ID: e9184708d96c
Revises: cdc3ed10934c
Create Date: 2019-02-26 23:17:14.556018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9184708d96c'
down_revision = 'cdc3ed10934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('device_token', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'app_user', ['device_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='unique')
    op.drop_column('app_user', 'device_token')
    # ### end Alembic commands ###
