"""empty message

Revision ID: f990a25203be
Revises: 17e3ca31d5ab
Create Date: 2019-04-10 17:54:48.054021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f990a25203be'
down_revision = '17e3ca31d5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('chat_muted', sa.Boolean(), nullable=True, server_default=sa.text("FALSE")))
    op.add_column('app_user', sa.Column('tasks_muted', sa.Boolean(), nullable=True, server_default=sa.text("FALSE")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'tasks_muted')
    op.drop_column('app_user', 'chat_muted')
    # ### end Alembic commands ###
