"""empty message

Revision ID: 17e3ca31d5ab
Revises: 02dcb9c673d9
Create Date: 2019-04-08 15:29:24.263664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e3ca31d5ab'
down_revision = '02dcb9c673d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistee_member_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['assistee_member_id'], ['team_member.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assist')
    # ### end Alembic commands ###
