"""empty message

Revision ID: cdc3ed10934c
Revises: af6a3f50b8c5
Create Date: 2019-02-18 21:12:09.745782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc3ed10934c'
down_revision = 'af6a3f50b8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('grade', sa.Integer(), nullable=True))
    op.alter_column("task", "due_date",
        type_ = sa.types.DateTime(timezone=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'grade')
    op.alter_column("task", "due_date",
        type_ = sa.types.DateTime(timezone=True))
    # ### end Alembic commands ###
