"""empty message

Revision ID: b3808a8afcb5
Revises: f990a25203be
Create Date: 2019-04-10 19:34:24.614776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3808a8afcb5'
down_revision = 'f990a25203be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('chat_notifs', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('app_user', sa.Column('tasks_notifs', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.drop_column('app_user', 'tasks_muted')
    op.drop_column('app_user', 'chat_muted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('chat_muted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('app_user', sa.Column('tasks_muted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('app_user', 'tasks_notifs')
    op.drop_column('app_user', 'chat_notifs')
    # ### end Alembic commands ###
