"""empty message

Revision ID: 90bbfe8896f6
Revises: 0063af4db466
Create Date: 2019-03-28 17:35:09.762827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bbfe8896f6'
down_revision = '0063af4db466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'email')
    # ### end Alembic commands ###
