"""empty message

Revision ID: 416d16ed6116
Revises: 31b9572e3ac9
Create Date: 2019-03-03 05:48:57.891755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416d16ed6116'
down_revision = '31b9572e3ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('points_earned', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('points_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'points_total')
    op.drop_column('task', 'points_earned')
    # ### end Alembic commands ###
