"""empty message

Revision ID: c50e74da3356
Revises: 1fb32fc35709
Create Date: 2019-03-14 20:01:36.556116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e74da3356'
down_revision = '1fb32fc35709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_user_device_token_key', 'app_user', type_='unique')
    op.drop_constraint('app_user_firebase_token_key', 'app_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('app_user_firebase_token_key', 'app_user', ['firebase_token'])
    op.create_unique_constraint('app_user_device_token_key', 'app_user', ['device_token'])
    # ### end Alembic commands ###
