"""empty message

Revision ID: 731316b61e3e
Revises: b3808a8afcb5
Create Date: 2019-04-10 19:37:50.114493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731316b61e3e'
down_revision = 'b3808a8afcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('task_notifs', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.drop_column('app_user', 'tasks_notifs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('tasks_notifs', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('app_user', 'task_notifs')
    # ### end Alembic commands ###
