"""empty message

Revision ID: b61861a4b6e3
Revises: 6861bcb97478
Create Date: 2019-02-13 19:57:31.682658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61861a4b6e3'
down_revision = '6861bcb97478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('google_id', sa.String(length=128), unique=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'google_id')
    # ### end Alembic commands ###
