"""empty message

Revision ID: 6f992faf3b14
Revises: d61221a5bc5e
Create Date: 2018-11-27 14:53:16.124237

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime as dt


# revision identifiers, used by Alembic.
revision = '6f992faf3b14'
down_revision = 'd61221a5bc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False, server_default=dt.utcnow().strftime("%Y-%m-%d %H:%M:%S")))
    op.add_column('user', sa.Column('timezone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
