# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: pg-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 100M
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pg-db
  name: pg-volume-claim
spec:
  # storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M