# this file creates a Deployment and Service for the whole flask monolith

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: flask-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: ncernek/bricks:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secret
            - secretRef:
                name: firebase-auth-key
      imagePullSecrets:
        - name: regcred